name: cleanup

on:
  push:
    branches:
      - main

permissions: write-all

env:
 GH_TOKEN: ${{ github.token }}


jobs:
  cleanup:
    if: github.repository != 'ablil/python-starter-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash cleanup.sh ${{ github.actor }} $(basename ${{ github.repository }})
        shell: bash
