name: Main workflow

on:
  pull_request:
  release:
    types:
      - released
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Build source & built distributions
        run: |
          poetry version prerelease
          poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist
            README.md
            pyproject.toml

  publish-test-pypi:
    name: Publish to test PyPI
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - run: pip install poetry
      - name: configure test PyPI repository and publish
        continue-on-error: true # cant publish to same version without forcing it
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
      - run: poetry publish -r test-pypi

  publish-pypi:
    name: Publish to PyPI
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - run: pip install poetry
      - run: |
          poetry config repositories.pypi https://pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry publish -r pypi
